
package uy.edu.um;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int CARRITO = 13;
  public static final int PASOS = 4;
  public static final int CALORIAS_EQ = 15;
  public static final int DIFICULTAD = 10;
  public static final int ORIGEN = 9;
  public static final int CALORIAS = 7;
  public static final int PTO = 20;
  public static final int CM = 17;
  public static final int INGREDIENTES = 3;
  public static final int COL = 16;
  public static final int MENU = 14;
  public static final int ID = 22;
  public static final int CATEGORIAS = 8;
  public static final int NUM = 24;
  public static final int TIPO = 11;
  public static final int STRING = 21;
  public static final int SO = 18;
  public static final int EOF = 0;
  public static final int UNIDAD = 23;
  public static final int TIEMPO = 5;
  public static final int error = 1;
  public static final int SC = 19;
  public static final int PORCIONES = 6;
  public static final int RECETA = 2;
  public static final int RECETAS = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RECETA",
  "INGREDIENTES",
  "PASOS",
  "TIEMPO",
  "PORCIONES",
  "CALORIAS",
  "CATEGORIAS",
  "ORIGEN",
  "DIFICULTAD",
  "TIPO",
  "RECETAS",
  "CARRITO",
  "MENU",
  "CALORIAS_EQ",
  "COL",
  "CM",
  "SO",
  "SC",
  "PTO",
  "STRING",
  "ID",
  "UNIDAD",
  "NUM"
  };
}

